### ISSUE TITLE
Employee management

### ISSUE THREAD

**Issue by PauliusStankevicius** [Andrija121/MediaBazaarProjectKSAsolutions#7]

**Comment by Andrija121** [comment]
Users Can be added, edited and their status can become Inactive, in other words the users will be deleted from list of active users and will set as inactive. Which will mean that user's status is inactive and that user can only be seen in DB (e.x. user that stopped working, instead of deleting it we make it inactive and store its information in DB, so we have list with all information of employees ). We are supposed to hold  information for 7 years as it is in law of Netherlands
